echo "# Humanaxis.org" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/k3nkag5-dot/Humanaxis.org.git
git push -u origin main
